sudo: required
language: python
jdk: openjdk8
services:
  - docker
python:
  - 3.6
cache: pip
matrix:
  fast_finish: true

before_install:
  # PRs made to 'master' branch should always orginate from another repo or the 'dev' branch
  - '[ $TRAVIS_PULL_REQUEST = "false" ] || [ $TRAVIS_BRANCH != "master" ] || ([ $TRAVIS_PULL_REQUEST_SLUG = $TRAVIS_REPO_SLUG ] && [ $TRAVIS_PULL_REQUEST_BRANCH = "dev" ])'
  # Pull the docker image first so the test doesn't wait for this
  - docker pull nfcore/neutronstar
  - docker pull remiolsen/supernova
  # Fake the tag locally so that the pipeline runs properly
  - docker tag nfcore/neutronstar nfcore/neutronstar:latest

install:
  # Install Nextflow
  - mkdir /tmp/nextflow
  - cd /tmp/nextflow
  - wget -qO- get.nextflow.io | bash
  - sudo ln -s /tmp/nextflow/nextflow /usr/local/bin/nextflow
  # Install nf-core/tools
  - pip install nf-core
  # Reset
  - cd ${TRAVIS_BUILD_DIR}

env:
  - NXF_VER=0.31.1 # Specify a minimum NF version that should be tested and work
  #- NXF_VER='' # Plus: get the latest NF version and check, that it works

script:
  # Lint the pipeline code
  - nf-core lint ${TRAVIS_BUILD_DIR}
  # Run the busco_downloader script
  - cd ${TRAVIS_BUILD_DIR}/data/
  - python busco_data.py --help
  # Run the pipeline with the test profile
  - cd ${TRAVIS_BUILD_DIR}
  - nextflow run ${TRAVIS_BUILD_DIR} -profile standard,test --id testrun --maxreads all --fastqs . --genomesize 1000
