name: nf-core-neutronstar-1.0dev
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::busco=3.0.2
  - bioconda::multiqc=1.6
  - conda-forge::pip=18.1
  - pip:
    - quast==5.0.1
